apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ include "get.filename" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: copy-ssh-keys
          image: "{{ include "initContainerImage" . }}"
          command: ["sh", "-c"]
          args:
            - |
              cp /ssh-keys/ssh_host_ed25519_key /ssh-writable/ && \
              cp /ssh-keys/ssh_host_ed25519_key.pub /ssh-writable/ && \
              chmod 600 /ssh-writable/ssh_host_ed25519_key && \
              chmod 644 /ssh-writable/ssh_host_ed25519_key.pub
          volumeMounts:
            - name: ssh-ed25519-key
              mountPath: /ssh-keys
            - name: ssh-writable
              mountPath: /ssh-writable
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: interface-jenkins-internal-linux-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.internalLinux.ssh.port }}
          volumeMounts:
            - name: ssh-writable
              mountPath: {{ include "sshHostKeyPath" (dict "Values" .Values "pathKey" "internalLinux.ssh.hostKeyPath") | quote }}
              subPath: {{ include "sshHostKeyFileName" (dict "Values" .Values "pathKey" "internalLinux.ssh.hostKeyPath") | quote }}
              readOnly: true
            - name: ssh-writable
              mountPath: {{ include "sshHostKeyPubPath" (dict "Values" .Values "pathKey" "internalLinux.ssh.hostKeyPath") | quote }}
              subPath: {{ include "sshHostKeyPubFileName" (dict "Values" .Values "pathKey" "internalLinux.ssh.hostKeyPath") | quote }}
              readOnly: true
            - name: jenkins-public-key
              mountPath: /jenkins-public-key
              readOnly: true
      volumes:
        - name: ssh-ed25519-key
          secret:
            secretName: {{ .Values.interfaces.jenkins.name }}-{{ .Values.internalLinux.ssh.keySecretName }}
        - name: ssh-writable
          emptyDir: {}
        - name: jenkins-public-key
          secret:
            secretName: {{ .Values.interfaces.jenkins.name }}-{{ .Values.internalLinux.ssh.publicKeySecretName }}