apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-generate-ssh-keys
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.sshKeygenJob.name }}
      restartPolicy: OnFailure
      containers:
        - name: ssh-keygen
          image: "{{ .Values.sshKeygenJob.image.repository }}:{{ .Values.sshKeygenJob.image.tag }}"
          imagePullPolicy: {{ .Values.sshKeygenJob.image.imagePullPolicy}}
          command: ["/bin/bash", "-c", "/scripts/generate-ssh-secrets.sh"]
          envFrom:
            - configMapRef:
                name: interface-jenkins-internal-linux-config
          env:
            - name: INTERNAL_LINUX_HOST
              value: "internal-linux"
            - name: SSH_HOST_KEY_SECRET
              value: {{ .Values.internalLinux.sshKeySecretName }}
            - name: JENKINS_PRIVATE_KEY_SECRET
              value: {{ .Values.internalLinux.jenkinsPrivateKeySecretName }}
            - name: JENKINS_PUBLIC_KEY_SECRET
              value: {{ .Values.internalLinux.jenkinsPublicKeySecretName }}
            - name: UPDATES_DOWNLOADER_KNOWN_HOSTS_SECRET
              value: {{ .Values.internalLinux.knownHostsSecretName }}
            - name: SSH_HOST_KEY_PATH
              value: {{ .Values.internalLinux.ssh.hostKeyPath }}
            - name: UPDATES_DOWNLOADER_HOST
              value: "internal-linux"
            - name: JENKINS_SSH_USER_NAME
              value: {{ .Values.internalLinux.ssh.jenkinsUsername }}
