apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ include "get.filename" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "configMapName" . }}
          ports:
            - containerPort: 8080
          env:
            - name: JENKINS_ADMIN_ID
              value: "admin"
            - name: JENKINS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-admin
                  key: password
            {{- range .Values.env0 }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.env1 }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}          
            - name: UPDATES_DOWNLOADER_SSH_JENKINS_USERNAME
              value: "{{ .Values.updatesDownloader.sshJenkinsUsername }}"
            - name: INTERNAL_LINUX_SSH_JENKINS_USERNAME
              value: "{{ .Values.internalLinux.ssh.jenkinsUsername }}"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      initContainers:
        - name: setup-ssh
          image: "{{ include "initContainerImage" . }}"
          envFrom:
            - configMapRef:
                name: {{ include "configMapName" . }}
          command: ["sh", "-c"]
          # TODO: convert this to a set of scripts
          args:
            - |
              # Remove any existing SSH keys
              rm -rf $SSH_FOLDER_PATH

              mkdir -p $SSH_FOLDER_PATH
              chmod 700 $SSH_FOLDER_PATH

              # Copy SSH keys with proper permissions
              # cp /updates-downloader-ssh-key/id_ed25519 $SSH_FOLDER_PATH/updates_downloader_id_ed25519
              # chmod 600 $SSH_FOLDER_PATH/updates_downloader_id_ed25519

              cp /{{ include "internal-linux.ssh-key.secret-name" . }}/id_ed25519 $INTERNAL_LINUX_KEY_FILE_PATH
              chmod 600 $INTERNAL_LINUX_KEY_FILE_PATH

              # Copy known_hosts with proper permissions
              # cp /updates-downloader-known-hosts/known_hosts $SSH_FOLDER_PATH/updates_downloader_known_hosts
              # chmod 644 $SSH_FOLDER_PATH/updates_downloader_known_hosts

              cp /{{ include "internal-linux.known-hosts.secret-name" . }}/known_hosts $SSH_FOLDER_PATH/internal_linux_known_hosts
              chmod 644 $SSH_FOLDER_PATH/internal_linux_known_hosts

              # Create SSH config
              echo "Host updates-downloader" > $SSH_FOLDER_PATH/config
              echo "  HostName updates-downloader" >> $SSH_FOLDER_PATH/config
              echo "  Port {{ .Values.updatesDownloader.sshPort }}" >> $SSH_FOLDER_PATH/config
              echo "  User {{ .Values.updatesDownloader.sshJenkinsUsername }}" >> $SSH_FOLDER_PATH/config
              echo "  IdentityFile $SSH_FOLDER_PATH/updates_downloader_id_ed25519" >> $SSH_FOLDER_PATH/config
              echo "  UserKnownHostsFile $SSH_FOLDER_PATH/updates_downloader_known_hosts" >> $SSH_FOLDER_PATH/config
              echo "  StrictHostKeyChecking yes" >> $SSH_FOLDER_PATH/config
              echo "" >> $SSH_FOLDER_PATH/config
              echo "Host internal-linux-service" >> $SSH_FOLDER_PATH/config
              echo "  HostName internal-linux-service" >> $SSH_FOLDER_PATH/config
              echo "  Port {{ .Values.internalLinux.ssh.port }}" >> $SSH_FOLDER_PATH/config
              echo "  User {{ .Values.internalLinux.ssh.jenkinsUsername }}" >> $SSH_FOLDER_PATH/config
              echo "  IdentityFile $INTERNAL_LINUX_KEY_FILE_PATH" >> $SSH_FOLDER_PATH/config
              echo "  UserKnownHostsFile $SSH_FOLDER_PATH/internal_linux_known_hosts" >> $SSH_FOLDER_PATH/config
              echo "  StrictHostKeyChecking yes" >> $SSH_FOLDER_PATH/config
              chmod 600 $SSH_FOLDER_PATH/config

              # Set proper ownership for all files
              chown -R 1000:1000 $SSH_FOLDER_PATH
          volumeMounts:
            - name: jenkins-home
              mountPath: {{ .Values.jenkins.homePath }}
            # - name: updates-downloader-ssh-key
            #   mountPath: /updates-downloader-ssh-key
            #   readOnly: true
            # - name: updates-downloader-known-hosts
            #   mountPath: /updates-downloader-known-hosts
            #   readOnly: true
            - name: {{ include "internal-linux.ssh-key.secret-name" . }}
              mountPath: /{{ include "internal-linux.ssh-key.secret-name" . }}
              readOnly: true
            - name: {{ include "internal-linux.known-hosts.secret-name" . }}
              mountPath: /{{ include "internal-linux.known-hosts.secret-name" . }}
              readOnly: true
      volumes:
        # - name: updates-downloader-ssh-key
        #   secret:
        #     secretName: {{ .Values.updatesDownloader.jenkinsPrivateKeySecretName }}
        #     defaultMode: 0600
        # - name: updates-downloader-known-hosts
        #   secret:
        #     secretName: {{ .Values.updatesDownloader.knownHostsSecretName }}
        #     defaultMode: 0644
        - name: {{ include "internal-linux.ssh-key.secret-name" . }}
          secret:
            secretName: {{ include "internal-linux.ssh-key.secret-name" . }}
            defaultMode: 0600
        - name: {{ include "internal-linux.known-hosts.secret-name" . }}
          secret:
            secretName: {{ include "internal-linux.known-hosts.secret-name" . }}
            defaultMode: 0644
        # TODO: do we need this volume to be persistent?
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc