apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JENKINS_ADMIN_ID
              value: "admin"
            - name: JENKINS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-admin
                  key: password
            {{- range .Values.env0 }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.env1 }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}          
            - name: UPDATES_DOWNLOADER_SSH_JENKINS_USERNAME
              value: "{{ .Values.updatesDownloader.sshJenkinsUsername }}"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-ssh-key
              mountPath: /var/jenkins_home/.ssh/id_ed25519
              subPath: id_ed25519
              readOnly: true
            - name: jenkins-known-hosts
              mountPath: /var/jenkins_home/.ssh/known_hosts
              subPath: known_hosts
              readOnly: true
      volumes:
        - name: jenkins-ssh-key
          secret:
            secretName: {{ .Values.updatesDownloader.jenkinsPrivateKeySecretName }}
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: jenkins-known-hosts
          secret:
            secretName: {{ .Values.updatesDownloader.knownHostsSecretName }}
        - name: ssh-ed25519-key
          secret:
            secretName: {{ .Values.updatesDownloader.sshKeySecretName }}
        - name: jenkins-ssh-dir
          emptyDir: {}
      initContainers:
        - name: copy-jenkins-ssh-key
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          command: ["sh", "-c"]
          args:
            - |
              cp /ssh-keys/ssh_host_ed25519_key /jenkins-ssh/id_ed25519 && \
              chmod 600 /jenkins-ssh/id_ed25519
          volumeMounts:
            - name: ssh-ed25519-key
              mountPath: /ssh-keys
            - name: jenkins-ssh-dir
              mountPath: /jenkins-ssh