replicaCount: 1
image:
  repository: nexus-repo
  tag: "latest"
  pullPolicy: IfNotPresent
initJobContainer:
  image:
    repository: curlimages/curl
    tag: "8.8.0"
service:
  type: NodePort
  port: 8081
  nodePort: 32009
readinessProbe:
  enabled: true
  path: /service/rest/v1/status
  initialDelaySeconds: 90  # Allow slow initial startup
  periodSeconds: 20
  failureThreshold: 6
env:
  NEXUS_CONTEXT: /nexus      
resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"
persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
# TODO: move to utils?
configMap:
  name: "config"
adminUser:
  name: "admin"
adminPassword:
  secretName: admin-password
  keyName: password