replicaCount: 1
image:
  repository: nexus-repo
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8081
  nodePort: 32009
  timeout: 300
  checkNexusReadySleep: 5
env:
  NEXUS_CONTEXT: /nexus      
resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"
persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
# TODO: move to utils?
configMap:
  name: "config"
adminUser:
  name: "admin"
adminPassword:
  secretName: admin-password
  keyName: password 