replicaCount: 1

image:
  repository: internal-linux
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

internalLinux:
  sshKeySecretName: "internal-linux-ssh-host-key"
  jenkinsPrivateKeySecretName: "internal-linux-jenkins-private-key"
  jenkinsPublicKeySecretName: "internal-linux-jenkins-public-key"
  knownHostsSecretName: "internal-linux-known-hosts"

sshKeygenJob:
  name: internal-linux-ssh-keygen
  image:
    repository: create-ssh-secret
    tag: latest
    imagePullPolicy: IfNotPresent

initContainer:
  image:
    repository: busybox
    tag: "1.36"