apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configMapName" . }}
  labels:
    {{- include "interface.labels" . | nindent 4 }}
    protocol: ssh
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-50"
data:
  LOG_LEVEL: "DEBUG"
  UPDATES_DOWNLOADER_SSH_PORT: "{{ .Values.updatesDownloader.ssh.port }}"
  UPDATES_DOWNLOADER_SSH_JENKINS_USERNAME: "{{ .Values.updatesDownloader.ssh.jenkinsUsername }}"
  SSH_HOST_KEY_PATH: {{ include "sshHostKeyPath" (dict "path" .Values.updatesDownloader.ssh.hostKeyPath) | quote }}
  SSH_HOST_KEY_PUB_PATH: {{ include "sshHostKeyPubPath" (dict "path" .Values.updatesDownloader.ssh.hostKeyPath) | quote }}
  SSH_KEY_ALGORITHM: "{{ .Values.updatesDownloader.ssh.hostKeyPath.algorithm }}"
  UPDATES_DOWNLOADER_SSH_PUBLIC_KEY_SECRET: {{ .Release.Name }}-{{ .Values.updatesDownloader.ssh.publicKeySecretName }}
