apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.fullname" . }}-admin
  labels:
    app: {{ include "jenkins.name" . }}
type: Opaque
data:
  password: {{ .Values.adminPassword | b64enc | quote }}
