apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ include "get.filename" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.nexus.userID }}
            runAsGroup: {{ .Values.nexus.groupID }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          env:
            - name: TARGET_HOST
              value: "localhost"
            - name: TARGET_PORT
              value: {{ .Values.service.port | quote }}
            - name: TARGET_PATH
              value: {{ .Values.readinessProbe.path | quote }}
            - name: PERIOD_SECONDS
              value: {{ .Values.readinessProbe.periodSeconds | quote }}
            - name: FAILURE_THRESHOLD
              value: {{ .Values.readinessProbe.failureThreshold | quote }}
            - name: INITIAL_DELAY_SECONDS
              value: {{ .Values.readinessProbe.initialDelaySeconds | quote }}
          envFrom:
            {{- include "envFromConfigMaps" . | nindent 12 }}
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
            {{- include "volumeMounts.tmpMemVolumeMount" . | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: {{ .Values.initJobContainer.image.repository }}:{{ .Values.initJobContainer.image.tag }}
          securityContext:
            runAsUser: 0       # Run as root to allow chown
            runAsGroup: 0
            allowPrivilegeEscalation: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp {{ include "adminPasswordMountPath" . }}/{{ .Values.adminPassword.keyName }} {{ include "tmpMemAdminPasswordFilePath" . }}
              chmod 600 {{ include "tmpMemAdminPasswordFilePath" . }} && \
              chown {{ .Values.nexus.userID }}:{{ .Values.nexus.groupID }} {{ include "tmpMemAdminPasswordFilePath" . }}
          envFrom:
            {{- include "envFromConfigMaps" . | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.adminPassword.secretName }}
              mountPath: {{ include "adminPasswordMountPath" . | quote }}
              readOnly: true
            {{- include "volumeMounts.tmpMemVolumeMount" . | nindent 12 }}
      volumes:
        - name: {{ .Values.adminPassword.secretName }}
          secret:
            secretName: {{ .Values.adminPassword.secretName }}
        - name: {{ include "tmpMemVolumeName" . | quote }}
          emptyDir:
            medium: Memory
        - name: nexus-data
          emptyDir: {}