apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ include "get.filename" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
          - containerPort: {{ .Values.service.port }}
          readinessProbe:
            {{- if .Values.readinessProbe.enabled }}
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- end }}
          envFrom:
            {{- include "envFromConfigMaps" . | nindent 12 }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
        - name: {{ .Chart.Name }}-init
          image: {{ .Values.initJobContainer.image.repository }}:{{ .Values.initJobContainer.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - /scripts/init_nexus.sh
          env:
            - name: TARGET_HOST
              value: "localhost"
            - name: TARGET_PORT
              value: {{ .Values.service.port | quote }}
            - name: TARGET_PATH
              value: {{ .Values.readinessProbe.path | quote }}
            - name: PERIOD_SECONDS
              value: {{ .Values.readinessProbe.periodSeconds | quote }}
            - name: FAILURE_THRESHOLD
              value: {{ .Values.readinessProbe.failureThreshold | quote }}
            - name: INITIAL_DELAY_SECONDS
              value: {{ .Values.readinessProbe.initialDelaySeconds | quote }}
          envFrom:
            {{- include "envFromConfigMaps" . | nindent 12 }}
          volumeMounts:
            - name: nexus-scripts
              mountPath: /scripts
              readOnly: true
            - name: {{ .Values.adminPassword.secretName }}
              mountPath: /tmp/{{ .Values.adminPassword.secretName }}
              readOnly: true
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-scripts
          configMap:
            name: nexus-scripts
            defaultMode: 0755 # make the scripts executable
        - name: {{ .Values.adminPassword.secretName }}
          secret:
            secretName: {{ .Values.adminPassword.secretName }}
        - name: nexus-data
          emptyDir: {}