apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ include "get.filename" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: nexus-init
    spec:
      restartPolicy: Never
      containers:
        - name: nexus-init
          image: {{ .Values.initJobContainer.image.repository }}:{{ .Values.initJobContainer.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - /scripts/init_nexus.sh
          env:
            - name: TARGET_HOST
              value: {{ .Release.Name }}-service
            - name: TARGET_PORT
              value: {{ .Values.service.port | quote }}
            - name: TARGET_PATH
              value: {{ .Values.readinessProbe.path | quote }}
            - name: PERIOD_SECONDS
              value: {{ .Values.readinessProbe.periodSeconds | quote }}
            - name: FAILURE_THRESHOLD
              value: {{ .Values.readinessProbe.failureThreshold | quote }}
            - name: INITIAL_DELAY_SECONDS
              value: {{ .Values.readinessProbe.initialDelaySeconds | quote }}
          envFrom:
            {{- include "envFromConfigMaps" . | nindent 12 }}
          volumeMounts:
            - name: nexus-scripts
              mountPath: /scripts
              readOnly: true
            - name: {{ .Values.adminPassword.secretName }}
              mountPath: /tmp/{{ .Values.adminPassword.secretName }}
              readOnly: true
      volumes:
        - name: nexus-scripts
          configMap:
            name: nexus-scripts
            defaultMode: 0755 # make the scripts executable
        - name: {{ .Values.adminPassword.secretName }}
          secret:
            secretName: {{ .Values.adminPassword.secretName }}
