replicaCount: 1
image:
  repository: jenkins-controller
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 8080
  nodePort: 32008
persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 8Gi
adminPassword: "admin"
resources: {}
env:
  ADMIN_USER: admin
  ADMIN_PASSWORD: newpassword
  NEXUS_ADMIN_USER: admin
  NEXUS_ADMIN_PASSWORD: newpassword
  NEXUS_URL: "http://nexus-repo:8081"