apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: nexus
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nexus
      release: {{ .Release.Name }}
  template:
    metadata:
      name: nexus-pod
      labels:
        app: nexus
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nexus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env: []
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        - name: nexus-scripts
          mountPath: /scripts
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "/scripts/init_nexus.sh &"
      volumes:
      - name: nexus-data
        emptyDir: {}
      - name: nexus-scripts
        configMap:
          name: nexus-scripts
          defaultMode: 0755
