apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ include "get.filename" . }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.updatesDownloader.ssh.port }}
      targetPort: {{ .Values.updatesDownloader.ssh.port }}
      protocol: TCP
      name: ssh
  selector:
    app: {{ .Release.Name }}