apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-generate-ssh-keys
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.sshKeygenJob.name }}
      restartPolicy: OnFailure
      containers:
        - name: ssh-keygen
          image: "{{ .Values.sshKeygenJob.image.repository }}:{{ .Values.sshKeygenJob.image.tag }}"
          imagePullPolicy: {{ .Values.sshKeygenJob.image.imagePullPolicy}}
          command: ["sh", "-c"]
          args:
            - |
              export JENKINS_SSH_USER_NAME={{ .Values.updatesDownloader.sshJenkinsUsername }}
              export SSH_HOST_KEY_SECRET={{ .Values.updatesDownloader.sshKeySecretName }}
              export JENKINS_PRIVATE_KEY_SECRET={{ .Values.updatesDownloader.jenkinsPrivateKeySecretName }}
              export JENKINS_PUBLIC_KEY_SECRET={{ .Values.updatesDownloader.jenkinsPublicKeySecretName }}
              export UPDATES_DOWNLOADER_KNOWN_HOSTS_SECRET={{ .Values.updatesDownloader.knownHostsSecretName }}
              /scripts/generate-ssh-secrets.sh
        - name: UPDATES_DOWNLOADER_HOST
          value: "updates-downloader"
