# Define the port number once
x-port-number: &port-number 8081

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: nexus-repo
        ports:
        - containerPort: *port-number
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        - name: post-startup-script
          mountPath: /opt/scripts
        command: ["/bin/bash", "-c", "bin/nexus run & /opt/scripts/set_admin_credentials.sh"]
        env:
        - name: NEXUS_CONTEXT
          value: /nexus
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nexus-admin-credentials
              key: ADMIN_USER
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus-admin-credentials
              key: ADMIN_PASSWORD
        - name: NEW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus-admin-credentials
              key: NEW_PASSWORD
        - name: NEXUS_PORT
          valueFrom:
            configMapKeyRef:
              name: nexus-config
              key: NEXUS_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-data-pvc
      - name: post-startup-script
        configMap:
          name: post-startup-script
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus
  ports:
  - protocol: TCP
    port: *port-number
    targetPort: *port-number
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
