env0:
  - name: NEXUS_URL
    value: "http://nexus-repo:8081"
  - name: NEXUS_ADMIN_USER
    value: "admin"
  - name: NEXUS_ADMIN_PASSWORD
    value: "newpassword"
updatesDownloader:
  sshPort: 2222
  sshJenkinsUsername: jenkins
  sshKeySecretName: updates-downloader-ssh-host-keys
  jenkinsPrivateKeySecretName: jenkins-ssh-private-key
  jenkinsPublicKeySecretName: jenkins-ssh-public-key
  knownHostsSecretName: updates-downloader-known-hosts