labels:
  initiator: "jenkins"
  responder: "internal-linux"
internalLinux:
  ssh:
    port: 2222
    jenkinsUsername: "jenkins"
    hostKeyPath:
      prefix: "/etc/ssh/ssh_host_"
      algorithm: "ed25519"
      suffix: "_key"
      pubSuffix: ".pub"
    # hostKeyPath: "/etc/ssh/ssh_host_ed25519_key"
    keySecretName: "ssh-host-key"
    privateKeySecretName: "ssh-private-key"
    publicKeySecretName: "ssh-public-key"
    knownHostsSecretName: "ssh-known-hosts"
sshKeygenJob:
  roleName: ssh-keygen
  serviceAccountName: ssh-keygen
  image:
    repository: create-ssh-secret
    tag: latest
    imagePullPolicy: IfNotPresent
